/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
You allowed to use this component or parts of it under GPL terms
To use it on other terms or get Professional edition of the component please contact us at sales@dhtmlx.com
*/
window.dhtmlx||(dhtmlx={});dhtmlx.version="3.0";dhtmlx.codebase="./";dhtmlx.extend=function(a,b){for(var c in b)a[c]=b[c];b._init&&a._init();return a};
dhtmlx.proto_extend=function(){for(var a=arguments,b=a[0],c=[],d=a.length-1;d>0;d--){if(typeof a[d]=="function")a[d]=a[d].prototype;for(var e in a[d])e=="_init"?c.push(a[d][e]):b[e]||(b[e]=a[d][e])}a[0]._init&&c.push(a[0]._init);b._init=function(){for(var a=0;a<c.length;a++)c[a].apply(this,arguments)};b.base=a[1];var f=function(a){this._init(a);this._parseSettings&&this._parseSettings(a,this.defaults)};f.prototype=b;b=a=null;return f};dhtmlx.bind=function(a,b){return function(){return a.apply(b,arguments)}};
dhtmlx.require=function(a){dhtmlx._modules[a]||(dhtmlx.exec(dhtmlx.ajax().sync().get(dhtmlx.codebase+a).responseText),dhtmlx._modules[a]=!0)};dhtmlx._modules={};dhtmlx.exec=function(a){window.execScript?window.execScript(a):window.eval(a)};dhtmlx.methodPush=function(a,b){return function(){var c=!1;return c=a[b].apply(a,arguments)}};dhtmlx.isNotDefined=function(a){return typeof a=="undefined"};dhtmlx.delay=function(a,b,c,d){setTimeout(function(){var d=a.apply(b,c);a=b=c=null;return d},d||1)};
dhtmlx.uid=function(){if(!this._seed)this._seed=(new Date).valueOf();this._seed++;return this._seed};dhtmlx.toNode=function(a){return typeof a=="string"?document.getElementById(a):a};dhtmlx.toArray=function(a){return dhtmlx.extend(a||[],dhtmlx.PowerArray)};dhtmlx.toFunctor=function(a){return typeof a=="string"?eval(a):a};dhtmlx._events={};
dhtmlx.event=function(a,b,c,d){var a=dhtmlx.toNode(a),e=dhtmlx.uid();dhtmlx._events[e]=[a,b,c];d&&(c=dhtmlx.bind(c,d));a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c);return e};dhtmlx.eventRemove=function(a){if(a){var b=dhtmlx._events[a];b[0].removeEventListener?b[0].removeEventListener(b[1],b[2],!1):b[0].detachEvent&&b[0].detachEvent("on"+b[1],b[2]);delete this._events[a]}};
dhtmlx.EventSystem={_init:function(){this._events={};this._handlers={};this._map={}},block:function(){this._events._block=!0},unblock:function(){this._events._block=!1},mapEvent:function(a){dhtmlx.extend(this._map,a)},callEvent:function(a,b){if(this._events._block)return!0;var a=a.toLowerCase(),c=this._events[a.toLowerCase()],d=!0;if(c)for(var e=0;e<c.length;e++)if(c[e].apply(this,b||[])===!1)d=!1;this._map[a]&&!this._map[a].callEvent(a,b)&&(d=!1);return d},attachEvent:function(a,b,c){var a=a.toLowerCase(),
c=c||dhtmlx.uid(),b=dhtmlx.toFunctor(b),d=this._events[a]||dhtmlx.toArray();d.push(b);this._events[a]=d;this._handlers[c]={f:b,t:a};return c},detachEvent:function(a){if(this._handlers[a]){var b=this._handlers[a].t,c=this._handlers[a].f,d=this._events[b];d.remove(c);delete this._handlers[a]}}};
dhtmlx.PowerArray={removeAt:function(a,b){a>=0&&this.splice(a,b||1)},remove:function(a){this.removeAt(this.find(a))},insertAt:function(a,b){if(!b&&b!==0)this.push(a);else{var c=this.splice(b,this.length-b);this[b]=a;this.push.apply(this,c)}},find:function(a){for(i=0;i<this.length;i++)if(a==this[i])return i;return-1},each:function(a,b){for(var c=0;c<this.length;c++)a.call(b||this,this[c])},map:function(a,b){for(var c=0;c<this.length;c++)this[c]=a.call(b||this,this[c]);return this}};dhtmlx.env={};
if(navigator.userAgent.indexOf("Opera")!=-1)dhtmlx._isOpera=!0;else{dhtmlx._isIE=!!document.all;dhtmlx._isFF=!document.all;dhtmlx._isWebKit=navigator.userAgent.indexOf("KHTML")!=-1;if(navigator.appVersion.indexOf("MSIE 8.0")!=-1&&document.compatMode!="BackCompat")dhtmlx._isIE=8;if(navigator.appVersion.indexOf("MSIE 9.0")!=-1&&document.compatMode!="BackCompat")dhtmlx._isIE=8}dhtmlx.env={};
(function(){dhtmlx.env.transform=!1;dhtmlx.env.transition=!1;for(var a={names:["transform","transition"],transform:["transform","WebkitTransform","MozTransform","oTransform"],transition:["transition","WebkitTransition","MozTransition","oTransition"]},b=document.createElement("DIV"),c,d=0;d<a.names.length;d++)for(;p=a[a.names[d]].pop();)typeof b.style[p]!="undefined"&&(dhtmlx.env[a.names[d]]=!0)})();
dhtmlx.env.transform_prefix=function(){var a;dhtmlx._isOpera?a="-o-":(a="",dhtmlx._isFF&&(a="-moz-"),dhtmlx._isWebKit&&(a="-webkit-"));return a}();dhtmlx.env.svg=function(){return document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")}();dhtmlx.zIndex={drag:1E4};
dhtmlx.html={create:function(a,b,c){var b=b||{},d=document.createElement(a),e;for(e in b)d.setAttribute(e,b[e]);if(b.style)d.style.cssText=b.style;if(b["class"])d.className=b["class"];if(c)d.innerHTML=c;return d},getValue:function(a){a=dhtmlx.toNode(a);return!a?"":dhtmlx.isNotDefined(a.value)?a.innerHTML:a.value},remove:function(a){if(a instanceof Array)for(var b=0;b<a.length;b++)this.remove(a[b]);else a&&a.parentNode&&a.parentNode.removeChild(a)},insertBefore:function(a,b,c){a&&(b?b.parentNode.insertBefore(a,
b):c.appendChild(a))},locate:function(a,b){for(var a=a||event,c=a.target||a.srcElement;c;){if(c.getAttribute){var d=c.getAttribute(b);if(d)return d}c=c.parentNode}return null},offset:function(a){if(a.getBoundingClientRect){var b=a.getBoundingClientRect(),c=document.body,d=document.documentElement,e=window.pageYOffset||d.scrollTop||c.scrollTop,f=window.pageXOffset||d.scrollLeft||c.scrollLeft,g=d.clientTop||c.clientTop||0,h=d.clientLeft||c.clientLeft||0,k=b.top+e-g,j=b.left+f-h;return{y:Math.round(k),
x:Math.round(j)}}else{for(j=k=0;a;)k+=parseInt(a.offsetTop,10),j+=parseInt(a.offsetLeft,10),a=a.offsetParent;return{y:k,x:j}}},pos:function(a){a=a||event;if(a.pageX||a.pageY)return{x:a.pageX,y:a.pageY};var b=dhtmlx._isIE&&document.compatMode!="BackCompat"?document.documentElement:document.body;return{x:a.clientX+b.scrollLeft-b.clientLeft,y:a.clientY+b.scrollTop-b.clientTop}},preventEvent:function(a){a&&a.preventDefault&&a.preventDefault();dhtmlx.html.stopEvent(a)},stopEvent:function(a){(a||event).cancelBubble=
!0;return!1},addCss:function(a,b){a.className+=" "+b},removeCss:function(a,b){a.className=a.className.replace(RegExp(b,"g"),"")}};(function(){var a=document.getElementsByTagName("SCRIPT");if(a.length)a=(a[a.length-1].getAttribute("src")||"").split("/"),a.splice(a.length-1,1),dhtmlx.codebase=a.slice(0,a.length).join("/")+"/"})();if(!dhtmlx.ui)dhtmlx.ui={};
dhtmlx.Destruction={_init:function(){dhtmlx.destructors.push(this)},destructor:function(){this.destructor=function(){};this._htmlrows=this._htmlmap=null;this._html&&document.body.appendChild(this._html);this._html=null;if(this._obj)this._obj.innerHTML="",this._obj._htmlmap=null;this.data=this._obj=this._dataobj=null;this._events=this._handlers={}}};dhtmlx.destructors=[];
dhtmlx.event(window,"unload",function(){for(var a=0;a<dhtmlx.destructors.length;a++)dhtmlx.destructors[a].destructor();dhtmlx.destructors=[];for(var b in dhtmlx._events){var c=dhtmlx._events[b];c[0].removeEventListener?c[0].removeEventListener(c[1],c[2],!1):c[0].detachEvent&&c[0].detachEvent("on"+c[1],c[2]);delete dhtmlx._events[b]}});dhtmlx.math={};dhtmlx.math._toHex="0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F".split(",");
dhtmlx.math.toHex=function(a,b){a=parseInt(a,10);for(str="";a>0;)str=this._toHex[a%16]+str,a=Math.floor(a/16);for(;str.length<b;)str="0"+str;return str};dhtmlx.ui.Map=function(a){this.name="Map";this._id="map_"+dhtmlx.uid();this._key=a;this._map=[]};
dhtmlx.ui.Map.prototype={addRect:function(a,b,c){this._createMapArea(a,"RECT",b,c)},addPoly:function(a,b){this._createMapArea(a,"POLY",b)},_createMapArea:function(a,b,c,d){var e="";arguments.length==4&&(e="userdata='"+d+"'");this._map.push("<area "+this._key+"='"+a+"' shape='"+b+"' coords='"+c.join()+"' "+e+"></area>")},addSector:function(a,b,c,d,e,f,g){var h=[];h.push(d);h.push(Math.floor(e*g));for(var k=b;k<c;k+=Math.PI/18)h.push(Math.floor(d+f*Math.cos(k))),h.push(Math.floor((e+f*Math.sin(k))*
g));h.push(Math.floor(d+f*Math.cos(c)));h.push(Math.floor((e+f*Math.sin(c))*g));h.push(d);h.push(Math.floor(e*g));return this.addPoly(a,h)},render:function(a){var b=dhtmlx.html.create("DIV");b.style.cssText="position:absolute; width:100%; height:100%; top:0px; left:0px;";a.appendChild(b);var c=dhtmlx._isIE?"":"src='data:image/gif;base64,R0lGODlhEgASAIAAAP///////yH5BAUUAAEALAAAAAASABIAAAIPjI+py+0Po5y02ouz3pwXADs='";b.innerHTML="<map id='"+this._id+"' name='"+this._id+"'>"+this._map.join("\n")+"</map><img "+
c+" class='dhx_map_img' usemap='#"+this._id+"'>";a._htmlmap=b;this._map=[]}};dhtmlx.chart={};
dhtmlx.chart.area={pvt_render_area:function(a,b,c,d,e,f){var g=this._calculateParametersOfLineChart(a,b,c,d,e),h=Math.floor(g.cellWidth/2);if(b.length){a.globalAlpha=this._settings.alpha.call(this,b[0]);a.fillStyle=this._settings.color.call(this,b[0]);var k=this._getYPointOfLineChart(b[0],c,d,g),j=this._settings.offset?c.x+g.cellWidth*0.5:c.x;a.beginPath();a.moveTo(j,d.y);a.lineTo(j,k);f.addRect(b[0].id,[j-h,k-h,j+h,k+h]);this._settings.yAxis||this.renderTextAt(!1,!this._settings.offset?!1:!0,j,k-
this._settings.labelOffset,this._settings.label(b[0]));for(var i=1;i<b.length;i++){var m=j+Math.floor(g.cellWidth*i)-0.5,l=this._getYPointOfLineChart(b[i],c,d,g);a.lineTo(m,l);f.addRect(b[i].id,[m-h,l-h,m+h,l+h]);this._settings.yAxis||this.renderTextAt(!1,!this._settings.offset&&i==b.length-1?"left":"center",m,l-this._settings.labelOffset,this._settings.label(b[i]))}a.lineTo(j+Math.floor(g.cellWidth*[b.length-1]),d.y);a.lineTo(j,d.y);a.fill()}}};
dhtmlx.chart.stackedArea={pvt_render_stackedArea:function(a,b,c,d,e,f){var g=this._calculateParametersOfLineChart(a,b,c,d,e),h=Math.floor(g.cellWidth/2),k=[];if(b.length){a.globalAlpha=this._settings.alpha.call(this,b[0]);a.fillStyle=this._settings.color.call(this,b[0]);var j=e?b[0].$startY:d.y,i=this._settings.offset?c.x+g.cellWidth*0.5:c.x,m=this._getYPointOfLineChart(b[0],c,d,g)-(e?d.y-j:0);k[0]=m;a.beginPath();a.moveTo(i,j);a.lineTo(i,m);f.addRect(b[0].id,[i-h,m-h,i+h,m+h]);this._settings.yAxis||
this.renderTextAt(!1,!0,i,m-this._settings.labelOffset,this._settings.label(b[0]));for(var l=1;l<b.length;l++){var n=i+Math.floor(g.cellWidth*l)-0.5,o=this._getYPointOfLineChart(b[l],c,d,g)-(e?d.y-b[l].$startY:0);k[l]=o;a.lineTo(n,o);f.addRect(b[l].id,[n-h,o-h,n+h,o+h]);this._settings.yAxis||this.renderTextAt(!1,!0,n,o-this._settings.labelOffset,this._settings.label(b[l]))}a.lineTo(i+Math.floor(g.cellWidth*[b.length-1]),j);if(e)for(l=b.length-1;l>=0;l--){var n=i+Math.floor(g.cellWidth*l)-0.5,p=b[l].$startY;
a.lineTo(n,p)}else a.lineTo(i+Math.floor(g.cellWidth*(length-1))-0.5,j);a.lineTo(i,j);a.fill();for(l=0;l<b.length;l++)b[l].$startY=k[l]}}};
dhtmlx.chart.spline={pvt_render_spline:function(a,b,c,d,e){var f=this._calculateParametersOfLineChart(a,b,c,d,e),g=Math.floor(f.cellWidth/2),g=this._settings.eventRadius||g,h=[];if(b.length){for(var k=this._settings.offset?c.x+f.cellWidth*0.5:c.x,j=0;j<b.length;j++){var i=!j?k:Math.floor(f.cellWidth*j)-0.5+k,m=this._getYPointOfLineChart(b[j],c,d,f);h.push({x:i,y:m})}for(var l=this._getSplineParameters(h),j=0;j<h.length-1;j++){for(var n=h[j].x,o=h[j].y,p=h[j+1].x,q=h[j+1].y,t=n;t<p;t++)this._drawLine(a,
t,this._getSplineYPoint(t,n,j,l.a,l.b,l.c,l.d),t+1,this._getSplineYPoint(t+1,n,j,l.a,l.b,l.c,l.d),this._settings.line.color(b[j]),this._settings.line.width);this._drawLine(a,p-1,this._getSplineYPoint(t,n,j,l.a,l.b,l.c,l.d),p,q,this._settings.line.color(b[j]),this._settings.line.width);this._drawItemOfLineChart(a,n,o,b[j],this._settings.label(b[j]))}this._drawItemOfLineChart(a,p,q,b[j],this._settings.label(b[j]))}},_getSplineParameters:function(a){var b,c,d,e,f,g,h,k,j;b=[];m=[];j=a.length;for(var i=
0;i<j-1;i++)b[i]=a[i+1].x-a[i].x,m[i]=(a[i+1].y-a[i].y)/b[i];c=[];d=[];c[0]=0;c[1]=2*(b[0]+b[1]);d[0]=0;d[1]=6*(m[1]-m[0]);for(i=2;i<j-1;i++)c[i]=2*(b[i-1]+b[i])-b[i-1]*b[i-1]/c[i-1],d[i]=6*(m[i]-m[i-1])-b[i-1]*d[i-1]/c[i-1];e=[];e[j-1]=e[0]=0;for(i=j-2;i>=1;i--)e[i]=(d[i]-b[i]*e[i+1])/c[i];f=[];g=[];h=[];k=[];for(i=0;i<j-1;i++)f[i]=a[i].y,g[i]=-b[i]*e[i+1]/6-b[i]*e[i]/3+(a[i+1].y-a[i].y)/b[i],h[i]=e[i]/2,k[i]=(e[i+1]-e[i])/(6*b[i]);return{a:f,b:g,c:h,d:k}},_getSplineYPoint:function(a,b,c,d,e,f,g){return d[c]+
(a-b)*(e[c]+(a-b)*(f[c]+(a-b)*g[c]))}};
dhtmlx.chart.barH={pvt_render_barH:function(a,b,c,d,e,f){var g,h,k,j,i=d.x-c.x,m=!!this._settings.yAxis,l=!!this._settings.xAxis,n=this._getLimits("h");g=n.max;h=n.min;var o=Math.floor((d.y-c.y)/b.length);e||this._drawHScales(a,b,c,d,h,g,o);m&&(g=parseFloat(this._settings.xAxis.end),h=parseFloat(this._settings.xAxis.start));var p=this._getRelativeValue(h,g);j=p[0];k=p[1];var q=j?i/j:10;if(!m)var t=10,q=j?(i-t)/j:10;var s=parseInt(this._settings.width,10);s*this._series.length+4>o&&(s=o/this._series.length-
4);var C=Math.floor((o-s*this._series.length)/2),A=typeof this._settings.radius!="undefined"?parseInt(this._settings.radius,10):Math.round(s/5),x=!1,v=this._settings.gradient;v&&typeof v!="function"?(x=v,v=!1):v&&(v=a.createLinearGradient(c.x,c.y,d.x,c.y),this._settings.gradient(v));var B=0;m||this._drawLine(a,c.x-0.5,c.y,c.x-0.5,d.y,"#000000",1);for(var r=0;r<b.length;r++){var u=parseFloat(this._settings.value(b[r]||0));u>g&&(u=g);u-=h;u*=k;var w=c.x,y=c.y+C+r*o+(s+1)*e;if(u<0&&this._settings.origin==
"auto"||this._settings.xAxis&&u===0&&!(this._settings.origin!="auto"&&this._settings.origin>h))this.renderTextAt("middle","right",w+10,y+s/2+C,this._settings.label(b[r]));else{u<0&&this._settings.origin!="auto"&&this._settings.origin>h&&(u=0);m||(u+=t/q);var D=v||this._settings.color.call(this,b[r]);this._settings.border&&this._drawBarHBorder(a,w,y,s,h,A,q,u,D);a.globalAlpha=this._settings.alpha.call(this,b[r]);var z=this._drawBarH(a,c,w,y,s,h,A,q,u,D,v,x);a.globalAlpha=1;x!=!1&&this._drawBarHGradient(a,
w,y,s,h,A,q,u,D,x);z[3]==y?(this.renderTextAt("middle","left",z[0]-5,z[3]+Math.floor(s/2),this._settings.label(b[r])),f.addRect(b[r].id,[z[0],z[3],z[2],z[3]+s],e)):(this.renderTextAt("middle",!1,z[2]+5,z[1]+Math.floor(s/2),this._settings.label(b[r])),f.addRect(b[r].id,[z[0],y,z[2],z[3]],e))}}},_setBarHPoints:function(a,b,c,d,e,f,g,h){var k=0;if(e>f*g)var j=(e-f*g)/e,k=-Math.asin(j)+Math.PI/2;a.moveTo(b,c+h);var i=b+f*g-e-(e?0:h);e<f*g&&a.lineTo(i,c+h);var m=c+e;e&&a.arc(i,m,e-h,-Math.PI/2+k,0,!1);
var l=c+d-e-(e?0:h),n=i+e-(e?h:0);a.lineTo(n,l);var o=i;e&&a.arc(o,l,e-h,0,Math.PI/2-k,!1);var p=c+d-h;a.lineTo(b,p);a.lineTo(b,c+h);return[n,p]},_drawHScales:function(a,b,c,d,e,f,g){var h=this._drawHXAxis(a,b,c,d,e,f);this._drawHYAxis(a,b,c,d,g,h)},_drawHYAxis:function(a,b,c,d,e,f){if(this._settings.yAxis){var g=parseInt(f?f:c.x,10)-0.5,h=d.y+0.5,k=c.y;this._drawLine(a,g,h,g,k,this._settings.yAxis.color,1);for(var j=0;j<b.length;j++){var i=this._settings.origin!="auto"&&this._settings.view=="barH"&&
parseFloat(this._settings.value(b[j]))<this._settings.origin;this.renderTextAt("middle",i?!1:"left",i?g+5:g-5,k+e/2+j*e,this._settings.yAxis.template(b[j]),"dhx_axis_item_y",i?0:g-10)}this._setYAxisTitle(c,d)}},_drawHXAxis:function(a,b,c,d,e,f){var g,h={},k=this._settings.xAxis;if(k){var j=d.y+0.5,i=c.x-0.5,m=d.x-0.5,l=c.x;this._drawLine(a,i,j,m,j,k.color,1);k.step&&(g=parseFloat(k.step));if(typeof k.step=="undefined"||typeof k.start=="undefined"||typeof k.end=="undefined")h=this._calculateScale(e,
f),e=h.start,f=h.end,g=h.step,this._settings.xAxis.end=f,this._settings.xAxis.start=e,this._settings.xAxis.step=g;if(g!==0){for(var n=(m-i)*g/(f-e),o=0,p=e;p<=f;p+=g){h.fixNum&&(p=parseFloat((new Number(p)).toFixed(h.fixNum)));var q=Math.floor(i+o*n)+0.5;!(p==e&&this._settings.origin=="auto")&&k.lines&&this._drawLine(a,q,j,q,c.y,this._settings.xAxis.color,0.2);p==this._settings.origin&&(l=q+1);this.renderTextAt(!1,!0,q,j+2,k.template(p.toString()),"dhx_axis_item_x");o++}this.renderTextAt(!0,!1,i,
d.y+this._settings.padding.bottom-3,this._settings.xAxis.title,"dhx_axis_title_x",d.x-c.x);k.lines||this._drawLine(a,i,c.y-0.5,m,c.y-0.5,this._settings.xAxis.color,0.2);return l}}},_correctBarHParams:function(a,b,c,d,e,f,g){var h=this._settings.yAxis,k=b;h&&this._settings.origin!="auto"&&this._settings.origin>g&&(b+=(this._settings.origin-g)*e,k=b,d-=this._settings.origin-g,d<0&&(d*=-1,a.translate(b,c+f),a.rotate(Math.PI),b=0.5,c=0),b+=0.5);return{value:d,x0:b,y0:c,start:k}},_drawBarH:function(a,
b,c,d,e,f,g,h,k,j,i,m){a.save();var l=this._correctBarHParams(a,c,d,k,h,e,f);a.fillStyle=j;a.beginPath();var n=this._setBarHPoints(a,l.x0,l.y0,e,g,h,l.value,this._settings.border?1:0);i&&!m&&a.lineTo(b.x+total_width,l.y0+(this._settings.border?1:0));a.fill();a.restore();var o=l.y0,p=l.y0!=d?d:n[1],q=l.y0!=d?l.start-n[0]:l.start,t=l.y0!=d?l.start:n[0];return[q,o,t,p]},_drawBarHBorder:function(a,b,c,d,e,f,g,h,k){a.save();var j=this._correctBarHParams(a,b,c,h,g,d,e);a.beginPath();a.fillStyle=k;this._setBarHPoints(a,
j.x0,j.y0,d,f,g,j.value,0);a.lineTo(b,0);a.fill();a.fillStyle="#000000";a.globalAlpha=0.37;a.beginPath();this._setBarHPoints(a,j.x0,j.y0,d,f,g,j.value,0);a.fill();a.restore()},_drawBarHGradient:function(a,b,c,d,e,f,g,h,k,j){a.save();var i=this._correctBarHParams(a,b,c,h,g,d,e),m=this._setBarGradient(a,i.x0,i.y0+d,i.x0+g*i.value,i.y0,j,k,"x");a.fillStyle=m.gradient;a.beginPath();var l=this._setBarHPoints(a,i.x0,i.y0+m.offset,d-m.offset*2,f,g,i.value,m.offset);a.fill();a.globalAlpha=1;a.restore()}};
dhtmlx.chart.stackedBarH={pvt_render_stackedBarH:function(a,b,c,d,e,f){var g,h,k,j,i=d.x-c.x,m=!!this._settings.yAxis,l=!!this._settings.xAxis,n=this._getStackedLimits(b);g=n.max;h=n.min;var o=Math.floor((d.y-c.y)/b.length);e||this._drawHScales(a,b,c,d,h,g,o);m&&(g=parseFloat(this._settings.xAxis.end),h=parseFloat(this._settings.xAxis.start));var p=this._getRelativeValue(h,g);j=p[0];k=p[1];var q=j?i/j:10;if(!m)var t=10,q=j?(i-t)/j:10;var s=parseInt(this._settings.width,10);s+4>o&&(s=o-4);var C=Math.floor((o-
s)/2),A=0,x=!1,v=this._settings.gradient,x=!1;(v=this._settings.gradient)&&(x=!0);var B=0;m||this._drawLine(a,c.x-0.5,c.y,c.x-0.5,d.y,"#000000",1);for(var r=0;r<b.length;r++){if(!e)b[r].$startX=c.x;var u=parseFloat(this._settings.value(b[r]||0));u>g&&(u=g);u-=h;u*=k;var w=c.x,y=c.y+C+r*o;if(e)w=b[r].$startX;if(u<0||this._settings.yAxis&&u===0)this.renderTextAt("middle",!0,w+10,y+s/2,this._settings.label(b[r]));else{m||(u+=t/q);var D=this._settings.color.call(this,b[r]);if(this._settings.border)a.beginPath(),
a.fillStyle=D,this._setBarHPoints(a,w,y,s,A,q,u,0),a.lineTo(w,0),a.fill(),a.fillStyle="#000000",a.globalAlpha=0.37,a.beginPath(),this._setBarHPoints(a,w,y,s,A,q,u,0),a.fill();a.globalAlpha=1;a.globalAlpha=this._settings.alpha.call(this,b[r]);a.fillStyle=this._settings.color.call(this,b[r]);a.beginPath();var z=this._setBarHPoints(a,w,y,s,A,q,u,this._settings.border?1:0);v&&!x&&a.lineTo(c.x+i,y+(this._settings.border?1:0));a.fill();if(x!=!1){var E=this._setBarGradient(a,w,y+s,w,y,x,D,"x");a.fillStyle=
E.gradient;a.beginPath();z=this._setBarHPoints(a,w,y,s,A,q,u,0);a.fill();a.globalAlpha=1}this.renderTextAt("middle",!0,b[r].$startX+(z[0]-b[r].$startX)/2-1,y+(z[1]-y)/2,this._settings.label(b[r]));f.addRect(b[r].id,[b[r].$startX,y,z[0],z[1]],e);b[r].$startX=z[0]}}}};
dhtmlx.chart.stackedBar={pvt_render_stackedBar:function(a,b,c,d,e,f){var g,h,k,j,i=d.y-c.y,m=!!this._settings.yAxis,l=!!this._settings.xAxis,n=this._getStackedLimits(b);g=n.max;h=n.min;var o=Math.floor((d.x-c.x)/b.length);e||this._drawScales(a,b,c,d,h,g,o);m&&(g=parseFloat(this._settings.yAxis.end),h=parseFloat(this._settings.yAxis.start));var p=this._getRelativeValue(h,g);j=p[0];k=p[1];var q=j?i/j:10,t=parseInt(this._settings.width,10);t+4>o&&(t=o-4);var s=Math.floor((o-t)/2),C=this._settings.gradient?
this._settings.gradient:!1,A=0;l||this._drawLine(a,c.x,d.y+0.5,d.x,d.y+0.5,"#000000",1);for(var x=0;x<b.length;x++){var v=parseFloat(this._settings.value(b[x]||0));if(v){e||(v-=h);v*=k;var B=c.x+s+x*o,r=d.y;if(e)r=b[x].$startY;if(!(r<c.y+1))if(v<0||this._settings.yAxis&&v===0)this.renderTextAt(!0,!0,B+Math.floor(t/2),r,this._settings.label(b[x]));else{var u=this._settings.color.call(this,b[x]);if(this._settings.border)a.beginPath(),a.fillStyle=u,this._setStakedBarPoints(a,B-1,r,t+2,q,v,0,c.y),a.lineTo(B,
r),a.fill(),a.fillStyle="#000000",a.globalAlpha=0.37,a.beginPath(),this._setStakedBarPoints(a,B-1,r,t+2,q,v,0,c.y),a.fill();a.globalAlpha=this._settings.alpha.call(this,b[x]);a.fillStyle=this._settings.color.call(this,b[x]);a.beginPath();var w=this._setStakedBarPoints(a,B,r,t,q,v,this._settings.border?1:0,c.y);a.fill();a.globalAlpha=1;if(C){var y=this._setBarGradient(a,B,r,B+t,w[1],C,u,"y");a.fillStyle=y.gradient;a.beginPath();w=this._setStakedBarPoints(a,B+y.offset,r,t-y.offset*2,q,v,this._settings.border?
1:0,c.y);a.fill();a.globalAlpha=1}this.renderTextAt(!1,!0,B+Math.floor(t/2),w[1]+(r-w[1])/2-7,this._settings.label(b[x]));f.addRect(b[x].id,[B,w[1],w[0],b[x].$startY||r],e);b[x].$startY=this._settings.border?w[1]+1:w[1]}}else if(!b[x].$startY)b[x].$startY=d.y}},_setStakedBarPoints:function(a,b,c,d,e,f,g,h){a.moveTo(b,c);var k=c-e*f+g;k<h&&(k=h);a.lineTo(b,k);var j=b+d,i=k;a.lineTo(j,i);var m=k,l=b+d;a.lineTo(l,c);a.lineTo(b,c);return[l,i-2*g]}};
dhtmlx.chart.line={pvt_render_line:function(a,b,c,d,e,f){var g=this._calculateParametersOfLineChart(a,b,c,d,e),h=this._settings.eventRadius||Math.floor(g.cellWidth/2);if(b.length)for(var k=this._getYPointOfLineChart(b[0],c,d,g),j=this._settings.offset?c.x+g.cellWidth*0.5:c.x,i=j,m=1;m<=b.length;m++){var l=Math.floor(g.cellWidth*m)-0.5+i;if(b.length!=m){var n=this._getYPointOfLineChart(b[m],c,d,g);this._drawLine(a,j,k,l,n,this._settings.line.color(b[m-1]),this._settings.line.width)}this._drawItemOfLineChart(a,
j,k,b[m-1],!!this._settings.offset);f.addRect(b[m-1].id,[j-h,k-h,j+h,k+h],e);k=n;j=l}},_drawItemOfLineChart:function(a,b,c,d,e){var f=parseInt(this._settings.item.radius,10);a.lineWidth=parseInt(this._settings.item.borderWidth,10);a.fillStyle=this._settings.item.color(d);a.strokeStyle=this._settings.item.borderColor(d);a.beginPath();a.arc(b,c,f,0,Math.PI*2,!0);a.fill();a.stroke();e&&this.renderTextAt(!1,!0,b,c-f-this._settings.labelOffset,this._settings.label(d))},_getYPointOfLineChart:function(a,
b,c,d){var e=d.minValue,f=d.maxValue,g=d.unit,h=d.valueFactor,k=this._settings.value(a),j=(parseFloat(k||0)-e)*h;this._settings.yAxis||(j+=d.startValue/g);var i=c.y-Math.floor(g*j);if(j<0)i=c.y;if(k>f)i=b.y;if(k<e)i=c.y;return i},_calculateParametersOfLineChart:function(a,b,c,d,e){var f={},g;f.totalHeight=d.y-c.y;f.cellWidth=Math.round((d.x-c.x)/(!this._settings.offset?b.length-1:b.length));var h=!!this._settings.yAxis,k=!!this._settings.xAxis,j=this._settings.view.indexOf("stacked")!=-1?this._getStackedLimits(b):
this._getLimits();f.maxValue=j.max;f.minValue=j.min;e||this._drawScales(a,b,c,d,f.minValue,f.maxValue,f.cellWidth);if(h)f.maxValue=parseFloat(this._settings.yAxis.end),f.minValue=parseFloat(this._settings.yAxis.start);var i=this._getRelativeValue(f.minValue,f.maxValue);g=i[0];f.valueFactor=i[1];f.unit=g?f.totalHeight/g:10;f.startValue=0;if(!h)f.startValue=f.unit>10?f.unit:10,f.unit=g?(f.totalHeight-f.startValue)/g:10;return f}};
dhtmlx.chart.bar={pvt_render_bar:function(a,b,c,d,e,f){var g,h,k,j,i=d.y-c.y,m=!!this._settings.yAxis,l=!!this._settings.xAxis,n=this._getLimits();g=n.max;h=n.min;var o=Math.floor((d.x-c.x)/b.length);!e&&(this._settings.origin=="auto"||m)&&this._drawScales(a,b,c,d,h,g,o);m&&(g=parseFloat(this._settings.yAxis.end),h=parseFloat(this._settings.yAxis.start));var p=this._getRelativeValue(h,g);j=p[0];k=p[1];var q=j?i/j:j;if(!m&&!(this._settings.origin!="auto"&&l))var t=10,q=j?(i-t)/j:t;!e&&this._settings.origin!=
"auto"&&!m&&this._settings.origin>h&&this._drawXAxis(a,b,c,d,o,d.y-q*(this._settings.origin-h));var s=parseInt(this._settings.width,10);this._series&&s*this._series.length+4>o&&(s=o/this._series.length-4);var C=Math.floor((o-s*this._series.length)/2),A=typeof this._settings.radius!="undefined"?parseInt(this._settings.radius,10):Math.round(s/5),x=!1,v=this._settings.gradient;v&&typeof v!="function"?(x=v,v=!1):v&&(v=a.createLinearGradient(0,d.y,0,c.y),this._settings.gradient(v));var B=0;l||this._drawLine(a,
c.x,d.y+0.5,d.x,d.y+0.5,"#000000",1);for(var r=0;r<b.length;r++){var u=parseFloat(this._settings.value(b[r]||0));u>g&&(u=g);u-=h;u*=k;var w=c.x+C+r*o+(s+1)*e,y=d.y;if(u<0||this._settings.yAxis&&u===0&&!(this._settings.origin!="auto"&&this._settings.origin>h))this.renderTextAt(!0,!0,w+Math.floor(s/2),y,this._settings.label(b[r]));else{!m&&!(this._settings.origin!="auto"&&l)&&(u+=t/q);var D=v||this._settings.color.call(this,b[r]);this._settings.border&&this._drawBarBorder(a,w,y,s,h,A,q,u,D);a.globalAlpha=
this._settings.alpha.call(this,b[r]);var z=this._drawBar(a,c,w,y,s,h,A,q,u,D,v,x);a.globalAlpha=1;x&&this._drawBarGradient(a,w,y,s,h,A,q,u,D,x);z[0]!=w?this.renderTextAt(!1,!0,w+Math.floor(s/2),z[1],this._settings.label(b[r])):this.renderTextAt(!0,!0,w+Math.floor(s/2),z[3],this._settings.label(b[r]));f.addRect(b[r].id,[w,z[3],z[2],z[1]],e)}}},_correctBarParams:function(a,b,c,d,e,f,g){var h=this._settings.xAxis,k=c;h&&this._settings.origin!="auto"&&this._settings.origin>g&&(c-=(this._settings.origin-
g)*e,k=c,d-=this._settings.origin-g,d<0&&(d*=-1,a.translate(b+f,c),a.rotate(Math.PI),c=b=0),c-=0.5);return{value:d,x0:b,y0:c,start:k}},_drawBar:function(a,b,c,d,e,f,g,h,k,j,i,m){a.save();a.fillStyle=j;var l=this._correctBarParams(a,c,d,k,h,e,f),n=this._setBarPoints(a,l.x0,l.y0,e,g,h,l.value,this._settings.border?1:0);i&&!m&&a.lineTo(l.x0+(this._settings.border?1:0),b.y);a.fill();a.restore();var o=l.x0,p=l.x0!=c?c+n[0]:n[0],q=l.x0!=c?l.start-n[1]:d,t=l.x0!=c?l.start:n[1];return[o,q,p,t]},_drawBarBorder:function(a,
b,c,d,e,f,g,h,k){a.save();var j=this._correctBarParams(a,b,c,h,g,d,e);a.fillStyle=k;this._setBarPoints(a,j.x0,j.y0,d,f,g,j.value,0);a.lineTo(j.x0,0);a.fill();a.fillStyle="#000000";a.globalAlpha=0.37;this._setBarPoints(a,j.x0,j.y0,d,f,g,j.value,0);a.fill();a.restore()},_drawBarGradient:function(a,b,c,d,e,f,g,h,k,j){a.save();var i=this._correctBarParams(a,b,c,h,g,d,e),m=this._setBarGradient(a,i.x0,i.y0,i.x0+d,i.y0-g*i.value+2,j,k,"y");a.fillStyle=m.gradient;this._setBarPoints(a,i.x0+m.offset,i.y0,d-
m.offset*2,f,g,i.value,m.offset);a.fill();a.restore()},_setBarPoints:function(a,b,c,d,e,f,g,h){a.beginPath();var k=0;if(e>f*g)var j=(e-f*g)/e,k=-Math.acos(j)+Math.PI/2;a.moveTo(b+h,c);var i=c-Math.floor(f*g)+e+(e?0:h);e<f*g&&a.lineTo(b+h,i);var m=b+e;e&&a.arc(m,i,e-h,-Math.PI+k,-Math.PI/2,!1);var l=b+d-e-(e?0:h),n=i-e+(e?h:0);a.lineTo(l,n);var o=i;e&&a.arc(l,o,e-h,-Math.PI/2,0-k,!1);var p=b+d-h;a.lineTo(p,c);a.lineTo(b+h,c);return[p,n]}};
dhtmlx.chart.pie={pvt_render_pie:function(a,b,c,d,e,f){this._renderPie(a,b,c,d,1,f)},_renderPie:function(a,b,c,d,e,f){if(b.length){for(var g=0,h=this._getPieParameters(c,d),k=this._settings.radius?this._settings.radius:h.radius,j=this.max(this._settings.value),i=[],m=[],l=0,n=0;n<b.length;n++)g+=parseFloat(this._settings.value(b[n])||0);for(n=0;n<b.length;n++)m[n]=parseFloat(this._settings.value(b[n])),i[n]=Math.PI*2*(g?(m[n]+l)/g:1/b.length),l+=m[n];var o=this._settings.x?this._settings.x:h.x,p=
this._settings.y?this._settings.y:h.y;e==1&&this._settings.shadow&&this._addShadow(a,o,p,k);p/=e;var q=-Math.PI/2;a.scale(1,e);for(n=0;n<b.length;n++)if(m[n]){a.lineWidth=2;a.beginPath();a.moveTo(o,p);alpha1=-Math.PI/2+i[n]-1.0E-4;a.arc(o,p,k,q,alpha1,!1);a.lineTo(o,p);var t=this._settings.color.call(this,b[n]);a.fillStyle=t;a.strokeStyle=this._settings.lineColor(b[n]);a.stroke();a.fill();this._settings.pieInnerText&&this._drawSectorLabel(o,p,5*k/6,q,alpha1,e,this._settings.pieInnerText(b[n],g),!0);
this._settings.label&&this._drawSectorLabel(o,p,k+this._settings.labelOffset,q,alpha1,e,this._settings.label(b[n]));if(e!=1)this._createLowerSector(a,o,p,q,alpha1,k,!0),a.fillStyle="#000000",a.globalAlpha=0.2,this._createLowerSector(a,o,p,q,alpha1,k,!1),a.globalAlpha=1,a.fillStyle=t;f.addSector(b[n].id,q,alpha1,o,p,k,e);q=alpha1}if(this._settings.gradient){var s=e!=1?o+k/3:o,C=e!=1?p+k/3:p;this._showRadialGradient(a,o,p,k,s,C)}a.scale(1,1/e)}},_getPieParameters:function(a,b){var c=b.x-a.x,d=b.y-a.y,
e=a.x+c/2,f=a.y+d/2,g=Math.min(c/2,d/2);return{x:e,y:f,radius:g}},_createLowerSector:function(a,b,c,d,e,f,g){a.lineWidth=1;if(d<=0&&e>=0||d>=0&&e<=Math.PI||d<=Math.PI&&e>=Math.PI){d<=0&&e>=0&&(d=0,g=!1,this._drawSectorLine(a,b,c,f,d,e));if(d<=Math.PI&&e>=Math.PI)e=Math.PI,g=!1,this._drawSectorLine(a,b,c,f,d,e);var h=(this._settings.height||Math.floor(f/4))/this._settings.cant;a.beginPath();a.arc(b,c,f,d,e,!1);a.lineTo(b+f*Math.cos(e),c+f*Math.sin(e)+h);a.arc(b,c+h,f,e,d,!0);a.lineTo(b+f*Math.cos(d),
c+f*Math.sin(d));a.fill();g&&a.stroke()}},_drawSectorLine:function(a,b,c,d,e,f){a.beginPath();a.arc(b,c,d,e,f,!1);a.stroke()},_addShadow:function(a,b,c,d){for(var e="#676767,#7b7b7b,#a0a0a0,#bcbcbc,#d1d1d1,#d6d6d6".split(","),f=e.length-1;f>-1;f--)a.beginPath(),a.fillStyle=e[f],a.arc(b+2,c+2,d+f,0,Math.PI*2,!0),a.fill()},_getGrayGradient:function(a){a.addColorStop(0,"#ffffff");a.addColorStop(0.7,"#7a7a7a");a.addColorStop(1,"#000000");return a},_showRadialGradient:function(a,b,c,d,e,f){a.globalAlpha=
0.3;a.beginPath();var g;typeof this._settings.gradient!="function"?(g=a.createRadialGradient(e,f,d/4,b,c,d),g=this._getGrayGradient(g)):g=this._settings.gradient(g);a.fillStyle=g;a.arc(b,c,d,0,Math.PI*2,!0);a.fill();a.globalAlpha=1},_drawSectorLabel:function(a,b,c,d,e,f,g,h){var k=this.renderText(0,0,g,0,1);if(k){var j=k.scrollWidth;k.style.width=j+"px";j>a&&(j=a);var i=8;h&&(i=j/1.8);var m=d+(e-d)/2;c-=(i-8)/2;var l=-i,n=-8,o="left";m>=Math.PI/2&&m<Math.PI&&(l=-j-l+1,o="right");m<=3*Math.PI/2&&m>=
Math.PI&&(l=-j-l+1,o="right");var p=(b+Math.floor(c*Math.sin(m)))*f+n,q=a+Math.floor((c+i/2)*Math.cos(m))+l,t=e<Math.PI/2+0.01,s=m<Math.PI/2;s&&t?q=Math.max(q,a+3):!s&&!t&&(q=Math.min(q,a-j));!h&&f<1&&p>b*f&&(p+=this._settings.height||Math.floor(c/4));k.style.top=p+"px";k.style.left=q+"px";k.style.width=j+"px";k.style.textAlign=o;k.style.whiteSpace="nowrap"}}};dhtmlx.chart.pie3D={pvt_render_pie3D:function(a,b,c,d,e,f){this._renderPie(a,b,c,d,this._settings.cant,f)}};
dhtmlx.Template={_cache:{},empty:function(){return""},setter:function(a){return dhtmlx.Template.fromHTML(a)},obj_setter:function(a){var b=dhtmlx.Template.setter(a),c=this;return function(){return b.apply(c,arguments)}},fromHTML:function(a){if(typeof a=="function")return a;if(this._cache[a])return this._cache[a];a=(a||"").toString();a=a.replace(/[\r\n]+/g,"\\n");a=a.replace(/\{obj\.([^}?]+)\?([^:]*):([^}]*)\}/g,'"+(obj.$1?"$2":"$3")+"');a=a.replace(/\{common\.([^}\(]*)\}/g,'"+common.$1+"');a=a.replace(/\{common\.([^\}\(]*)\(\)\}/g,
'"+(common.$1?common.$1(obj):"")+"');a=a.replace(/\{obj\.([^}]*)\}/g,'"+obj.$1+"');a=a.replace(/#([a-z0-9_]+)#/gi,'"+obj.$1+"');a=a.replace(/\{obj\}/g,'"+obj+"');a=a.replace(/\{-obj/g,"{obj");a=a.replace(/\{-common/g,"{common");a='return "'+a+'";';return this._cache[a]=Function("obj","common",a)}};
dhtmlx.Type={add:function(a,b){if(!a.types&&a.prototype.types)a=a.prototype;var c=b.name||"default";this._template(b);this._template(b,"edit");this._template(b,"loading");a.types[c]=dhtmlx.extend(dhtmlx.extend({},a.types[c]||this._default),b);return c},_default:{css:"default",template:function(){return""},template_edit:function(){return""},template_loading:function(){return"..."},width:150,height:80,margin:5,padding:0},_template:function(a,b){var b="template"+(b?"_"+b:""),c=a[b];if(c&&typeof c=="string"){if(c.indexOf("->")!=
-1)switch(c=c.split("->"),c[0]){case "html":c=dhtmlx.html.getValue(c[1]).replace(/\"/g,'\\"');break;case "http":c=(new dhtmlx.ajax).sync().get(c[1],{uid:(new Date).valueOf()}).responseText}a[b]=dhtmlx.Template.fromHTML(c)}}};
dhtmlx.SingleRender={_init:function(){},_toHTML:function(a){return this.type._item_start(a,this.type)+this.type.template(a,this.type)+this.type._item_end},render:function(){if(!this.callEvent||this.callEvent("onBeforeRender",[this.data])){if(this.data)this._dataobj.innerHTML=this._toHTML(this.data);this.callEvent&&this.callEvent("onAfterRender",[])}}};
dhtmlx.ui.Tooltip=function(a){this.name="Tooltip";this.version="3.0";typeof a=="string"&&(a={template:a});dhtmlx.extend(this,dhtmlx.Settings);dhtmlx.extend(this,dhtmlx.SingleRender);this._parseSettings(a,{type:"default",dy:0,dx:20});this._dataobj=this._obj=document.createElement("DIV");this._obj.className="dhx_tooltip";dhtmlx.html.insertBefore(this._obj,document.body.firstChild)};
dhtmlx.ui.Tooltip.prototype={show:function(a,b){if(!this._disabled){if(this.data!=a)this.data=a,this.render(a);this._obj.style.top=b.y+this._settings.dy+"px";this._obj.style.left=b.x+this._settings.dx+"px";this._obj.style.display="block"}},hide:function(){this.data=null;this._obj.style.display="none"},disable:function(){this._disabled=!0},enable:function(){this._disabled=!1},types:{"default":dhtmlx.Template.fromHTML("{obj.id}")},template_item_start:dhtmlx.Template.empty,template_item_end:dhtmlx.Template.empty};
dhtmlx.AutoTooltip={tooltip_setter:function(a){var b=new dhtmlx.ui.Tooltip(a);this.attachEvent("onMouseMove",function(a,d){b.show(this.get(a),dhtmlx.html.pos(d))});this.attachEvent("onMouseOut",function(){b.hide()});this.attachEvent("onMouseMoving",function(){b.hide()});return b}};dhtmlx.ajax=function(a,b,c){if(arguments.length!==0){var d=new dhtmlx.ajax;if(c)d.master=c;d.get(a,null,b)}return!this.getXHR?new dhtmlx.ajax:this};
dhtmlx.ajax.prototype={getXHR:function(){return dhtmlx.env.isIE?new ActiveXObject("Microsoft.xmlHTTP"):new XMLHttpRequest},send:function(a,b,c){var d=this.getXHR();typeof c=="function"&&(c=[c]);if(typeof b=="object"){var e=[],f;for(f in b){var g=b[f];if(g===null||g===dhtmlx.undefined)g="";e.push(f+"="+encodeURIComponent(g))}b=e.join("&")}b&&!this.post&&(a=a+(a.indexOf("?")!=-1?"&":"?")+b,b=null);d.open(this.post?"POST":"GET",a,!this._sync);this.post&&d.setRequestHeader("Content-type","application/x-www-form-urlencoded");
var h=this;d.onreadystatechange=function(){if(!d.readyState||d.readyState==4){if(c&&h)for(var a=0;a<c.length;a++)c[a]&&c[a].call(h.master||h,d.responseText,d.responseXML,d);c=h=h.master=null}};d.send(b||null);return d},get:function(a,b,c){this.post=!1;return this.send(a,b,c)},post:function(a,b,c){this.post=!0;return this.send(a,b,c)},sync:function(){this._sync=!0;return this}};
dhtmlx.AtomDataLoader={_init:function(a){this.data={};if(a)this._settings.datatype=a.datatype||"json",this._after_init.push(this._load_when_ready)},_load_when_ready:function(){this._ready_for_data=!0;this._settings.url&&this.url_setter(this._settings.url);this._settings.data&&this.data_setter(this._settings.data)},url_setter:function(a){if(!this._ready_for_data)return a;this.load(a,this._settings.datatype);return a},data_setter:function(a){if(!this._ready_for_data)return a;this.parse(a,this._settings.datatype);
return!0},load:function(a,b,c){this.callEvent("onXLS",[]);typeof b=="string"?(this.data.driver=dhtmlx.DataDriver[b],b=c):this.data.driver=dhtmlx.DataDriver.xml;dhtmlx.ajax(a,[this._onLoad,b],this)},parse:function(a,b){this.callEvent("onXLS",[]);this.data.driver=dhtmlx.DataDriver[b||"xml"];this._onLoad(a,null)},_onLoad:function(a,b){var c=this.data.driver,d=c.getRecords(c.toObject(a,b))[0];this.data=c?c.getDetails(d):a;this.callEvent("onXLE",[])},_check_data_feed:function(a){if(!this._settings.dataFeed||
this._ignore_feed||!a)return!0;var b=this._settings.dataFeed,b=b+(b.indexOf("?")==-1?"?":"&")+"action=get&id="+encodeURIComponent(a.id||a);this.callEvent("onXLS",[]);dhtmlx.ajax(b,function(a){this._ignore_feed=!0;this.setValues(dhtmlx.DataDriver.json.toObject(a)[0]);this._ignore_feed=!1;this.callEvent("onXLE",[])},this);return!1}};dhtmlx.DataDriver={};
dhtmlx.DataDriver.json={toObject:function(a){a||(a="[]");return typeof a=="string"?(eval("dhtmlx.temp="+a),dhtmlx.temp):a},getRecords:function(a){return a&&!(a instanceof Array)?[a]:a},getDetails:function(a){return a},getInfo:function(a){return{_size:a.total_count||0,_from:a.pos||0}}};
dhtmlx.DataDriver.json_ext={toObject:function(a){a||(a="[]");if(typeof a=="string"){var b;eval("temp="+a);dhtmlx.temp=[];for(var c=b.header,d=0;d<b.data.length;d++){for(var e={},f=0;f<c.length;f++)typeof b.data[d][f]!="undefined"&&(e[c[f]]=b.data[d][f]);dhtmlx.temp.push(e)}return dhtmlx.temp}return a},getRecords:function(a){return a&&!(a instanceof Array)?[a]:a},getDetails:function(a){return a},getInfo:function(a){return{_size:a.total_count||0,_from:a.pos||0}}};
dhtmlx.DataDriver.html={toObject:function(a){if(typeof a=="string"){var b=null;a.indexOf("<")==-1&&(b=dhtmlx.toNode(a));if(!b)b=document.createElement("DIV"),b.innerHTML=a;return b.getElementsByTagName(this.tag)}return a},getRecords:function(a){return a.tagName?a.childNodes:a},getDetails:function(a){return dhtmlx.DataDriver.xml.tagToObject(a)},getInfo:function(){return{_size:0,_from:0}},tag:"LI"};
dhtmlx.DataDriver.jsarray={toObject:function(a){return typeof a=="string"?(eval("dhtmlx.temp="+a),dhtmlx.temp):a},getRecords:function(a){return a},getDetails:function(a){for(var b={},c=0;c<a.length;c++)b["data"+c]=a[c];return b},getInfo:function(){return{_size:0,_from:0}}};
dhtmlx.DataDriver.csv={toObject:function(a){return a},getRecords:function(a){return a.split(this.row)},getDetails:function(a){for(var a=this.stringToArray(a),b={},c=0;c<a.length;c++)b["data"+c]=a[c];return b},getInfo:function(){return{_size:0,_from:0}},stringToArray:function(a){for(var a=a.split(this.cell),b=0;b<a.length;b++)a[b]=a[b].replace(/^[ \t\n\r]*(\"|)/g,"").replace(/(\"|)[ \t\n\r]*$/g,"");return a},row:"\n",cell:","};
dhtmlx.DataDriver.xml={toObject:function(a,b){return b&&(b=this.checkResponse(a,b))?b:typeof a=="string"?this.fromString(a):a},getRecords:function(a){return this.xpath(a,this.records)},records:"/*/item",getDetails:function(a){return this.tagToObject(a,{})},getInfo:function(a){return{_size:a.documentElement.getAttribute("total_count")||0,_from:a.documentElement.getAttribute("pos")||0}},xpath:function(a,b){if(window.XPathResult){var c=a;if(a.nodeName.indexOf("document")==-1)a=a.ownerDocument;for(var d=
[],e=a.evaluate(b,c,null,XPathResult.ANY_TYPE,null),f=e.iterateNext();f;)d.push(f),f=e.iterateNext();return d}else{var g=!0;try{typeof a.selectNodes=="undefined"&&(g=!1)}catch(h){}if(g)return a.selectNodes(b);else{var k=b.split("/").pop();return a.getElementsByTagName(k)}}},tagToObject:function(a,b){var b=b||{},c=!1,d=a.attributes;if(d&&d.length){for(var e=0;e<d.length;e++)b[d[e].name]=d[e].value;c=!0}for(var f=a.childNodes,g={},e=0;e<f.length;e++)if(f[e].nodeType==1){var h=f[e].tagName;typeof b[h]!=
"undefined"?(b[h]instanceof Array||(b[h]=[b[h]]),b[h].push(this.tagToObject(f[e],{}))):b[f[e].tagName]=this.tagToObject(f[e],{});c=!0}if(!c)return this.nodeValue(a);b.value=this.nodeValue(a);return b},nodeValue:function(a){return a.firstChild?a.firstChild.data:""},fromString:function(a){if(window.DOMParser&&!dhtmlx._isIE)return(new DOMParser).parseFromString(a,"text/xml");if(window.ActiveXObject){var b=new ActiveXObject("Microsoft.xmlDOM");b.loadXML(a);return b}},checkResponse:function(a,b){if(b&&
b.firstChild&&b.firstChild.tagName!="parsererror")return b;var c=this.fromString(a.replace(/^[\s]+/,""));if(c)return c}};
dhtmlx.DataLoader={_init:function(a){a=a||"";name="DataStore";this.data=a.datastore||new dhtmlx.DataStore;this._readyHandler=this.data.attachEvent("onStoreLoad",dhtmlx.bind(this._call_onready,this))},load:function(a,b){dhtmlx.AtomDataLoader.load.apply(this,arguments);if(!this.data.feed)this.data.feed=function(b,d){if(this._load_count)return this._load_count=[b,d];else this._load_count=!0;this.load(a+(a.indexOf("?")==-1?"?":"&")+"posStart="+b+"&count="+d,function(){var a=this._load_count;this._load_count=
!1;typeof a=="object"&&this.data.feed.apply(this,a)})}},_onLoad:function(a,b){this.data._parse(this.data.driver.toObject(a,b));this.callEvent("onXLE",[]);if(this._readyHandler)this.data.detachEvent(this._readyHandler),this._readyHandler=null},dataFeed_setter:function(a){this.data.attachEvent("onBeforeFilter",dhtmlx.bind(function(a,c){if(this._settings.dataFeed){var d={};if(a||d){if(typeof a=="function"){if(!c)return;a(c,d)}else d={text:c};this.clearAll();var e=this._settings.dataFeed,f=[],g;for(g in d)f.push("dhx_filter["+
g+"]="+encodeURIComponent(d[g]));this.load(e+(e.indexOf("?")<0?"?":"&")+f.join("&"),this._settings.datatype);return!1}}},this));return a},_call_onready:function(){if(this._settings.ready){var a=dhtmlx.toFunctor(this._settings.ready);a&&a.call&&a.apply(this,arguments)}}};dhtmlx.DataStore=function(){this.name="DataStore";dhtmlx.extend(this,dhtmlx.EventSystem);this.setDriver("xml");this.pull={};this.order=dhtmlx.toArray()};
dhtmlx.DataStore.prototype={setDriver:function(a){this.driver=dhtmlx.DataDriver[a]},_parse:function(a){this.callEvent("onParse",[this.driver,a]);this._filter_order&&this.filter();var b=this.driver.getInfo(a),c=this.driver.getRecords(a),d=(b._from||0)*1;if(d===0&&this.order[0])d=this.order.length;for(var e=0,f=0;f<c.length;f++){var g=this.driver.getDetails(c[f]),h=this.id(g);this.pull[h]||(this.order[e+d]=h,e++);this.pull[h]=g;this.extraParser&&this.extraParser(g);this._scheme&&(this._scheme.$init?
this._scheme.$update(g):this._scheme.$update&&this._scheme.$update(g))}for(f=0;f<b._size;f++)this.order[f]||(h=dhtmlx.uid(),g={id:h,$template:"loading"},this.pull[h]=g,this.order[f]=h);this.callEvent("onStoreLoad",[this.driver,a]);this.refresh()},id:function(a){return a.id||(a.id=dhtmlx.uid())},changeId:function(a,b){this.pull[b]=this.pull[a];this.pull[b].id=b;this.order[this.order.find(a)]=b;this._filter_order&&(this._filter_order[this._filter_order.find(a)]=b);this.callEvent("onIdChange",[a,b]);
this._render_change_id&&this._render_change_id(a,b)},get:function(a){return this.item(a)},set:function(a,b){return this.update(a,b)},item:function(a){return this.pull[a]},update:function(a,b){this._scheme&&this._scheme.$update&&this._scheme.$update(b);if(this.callEvent("onBeforeUpdate",[a,b])===!1)return!1;this.pull[a]=b;this.refresh(a)},refresh:function(a){this._skip_refresh||(a?this.callEvent("onStoreUpdated",[a,this.pull[a],"update"]):this.callEvent("onStoreUpdated",[null,null,null]))},silent:function(a){this._skip_refresh=
!0;a.call(this);this._skip_refresh=!1},getRange:function(a,b){a=a?this.indexById(a):this.startOffset||0;b?b=this.indexById(b):(b=Math.min(this.endOffset||Infinity,this.dataCount()-1),b<0&&(b=0));if(a>b)var c=b,b=a,a=c;return this.getIndexRange(a,b)},getIndexRange:function(a,b){for(var b=Math.min(b||Infinity,this.dataCount()-1),c=dhtmlx.toArray(),d=a||0;d<=b;d++)c.push(this.item(this.order[d]));return c},dataCount:function(){return this.order.length},exists:function(a){return!!this.pull[a]},move:function(a,
b){if(!(a<0||b<0)){var c=this.idByIndex(a),d=this.item(c);this.order.removeAt(a);this.order.insertAt(c,Math.min(this.order.length,b));this.callEvent("onStoreUpdated",[c,d,"move"])}},scheme:function(a){this._scheme=a},sync:function(a,b,c){typeof b!="function"&&(c=b,b=null);if(dhtmlx.debug_bind)this.debug_sync_master=a;if(a.name!="DataStore")a=a.data;var d=dhx.bind(function(d,f,g){if(g!="update"||b)d=null;if(!d)this.order=dhx.toArray([].concat(a.order)),this._filter_order=null,this.pull=a.pull,b&&this.silent(b),
this._on_sync&&this._on_sync();c?c=!1:this.refresh(d)},this);a.attachEvent("onStoreUpdated",d);d()},add:function(a,b){if(this._scheme){var a=a||{},c;for(c in this._scheme)a[c]=a[c]||this._scheme[c];this._scheme&&(this._scheme.$init?this._scheme.$update(a):this._scheme.$update&&this._scheme.$update(a))}var d=this.id(a),e=this.dataCount();if(dhtmlx.isNotDefined(b)||b<0)b=e;b>e&&(b=Math.min(this.order.length,b));if(this.callEvent("onBeforeAdd",[d,a,b])===!1)return!1;if(this.exists(d))return null;this.pull[d]=
a;this.order.insertAt(d,b);if(this._filter_order){var f=this._filter_order.length;!b&&this.order.length&&(f=0);this._filter_order.insertAt(d,f)}this.callEvent("onafterAdd",[d,b]);this.callEvent("onStoreUpdated",[d,a,"add"]);return d},remove:function(a){if(a instanceof Array)for(var b=0;b<a.length;b++)this.remove(a[b]);else{if(this.callEvent("onBeforeDelete",[a])===!1)return!1;if(!this.exists(a))return null;var c=this.item(a);this.order.remove(a);this._filter_order&&this._filter_order.remove(a);delete this.pull[a];
this.callEvent("onafterdelete",[a]);this.callEvent("onStoreUpdated",[a,c,"delete"])}},clearAll:function(){this.pull={};this.order=dhtmlx.toArray();this._filter_order=this.feed=null;this.callEvent("onClearAll",[]);this.refresh()},idByIndex:function(a){return this.order[a]},indexById:function(a){var b=this.order.find(a);return b},next:function(a,b){return this.order[this.indexById(a)+(b||1)]},first:function(){return this.order[0]},last:function(){return this.order[this.order.length-1]},previous:function(a,
b){return this.order[this.indexById(a)-(b||1)]},sort:function(a,b,c){var d=a;typeof a=="function"?d={as:a,dir:b}:typeof a=="string"&&(d={by:a,dir:b,as:c});var e=[d.by,d.dir,d.as];if(this.callEvent("onbeforesort",e)){if(this.order.length){var f=dhtmlx.sort.create(d),g=this.getRange(this.first(),this.last());g.sort(f);this.order=g.map(function(a){return this.id(a)},this)}this.refresh();this.callEvent("onaftersort",e)}},filter:function(a,b){if(this.callEvent("onBeforeFilter",[a,b])){if(this._filter_order)this.order=
this._filter_order,delete this._filter_order;if(this.order.length){if(a){var c=a,b=b||"";typeof a=="string"&&(a=dhtmlx.Template.fromHTML(a),b=b.toString().toLowerCase(),c=function(b,c){return a(b).toLowerCase().indexOf(c)!=-1});for(var d=dhtmlx.toArray(),e=0;e<this.order.length;e++){var f=this.order[e];c(this.item(f),b)&&d.push(f)}this._filter_order=this.order;this.order=d}this.refresh();this.callEvent("onAfterFilter",[])}}},each:function(a,b){for(var c=0;c<this.order.length;c++)a.call(b||this,this.item(this.order[c]))},
provideApi:function(a,b){this.debug_bind_master=a;b&&this.mapEvent({onbeforesort:a,onaftersort:a,onbeforeadd:a,onafteradd:a,onbeforedelete:a,onafterdelete:a,onbeforeupdate:a});for(var c="get,set,sort,add,remove,exists,idByIndex,indexById,item,update,refresh,dataCount,filter,next,previous,clearAll,first,last,serialize".split(","),d=0;d<c.length;d++)a[c[d]]=dhtmlx.methodPush(this,c[d])},serialize:function(){for(var a=this.order,b=[],c=0;c<a.length;c++)b.push(this.pull[a[c]]);return b}};
dhtmlx.sort={create:function(a){return dhtmlx.sort.dir(a.dir,dhtmlx.sort.by(a.by,a.as))},as:{"int":function(a,b){a*=1;b*=1;return a>b?1:a<b?-1:0},string_strict:function(a,b){a=a.toString();b=b.toString();return a>b?1:a<b?-1:0},string:function(a,b){a=a.toString().toLowerCase();b=b.toString().toLowerCase();return a>b?1:a<b?-1:0}},by:function(a,b){if(!a)return b;typeof b!="function"&&(b=dhtmlx.sort.as[b||"string"]);a=dhtmlx.Template.fromHTML(a);return function(c,d){return b(a(c),a(d))}},dir:function(a,
b){return a=="asc"?b:function(a,d){return b(a,d)*-1}}};
dhtmlx.Group={_init:function(){this.data.attachEvent("onStoreLoad",dhtmlx.bind(function(){this._settings.group&&this.group(this._settings.group,!1)},this));this.attachEvent("onBeforeRender",dhtmlx.bind(function(a){this._settings.sort&&(a.block(),a.sort(this._settings.sort),a.unblock())},this));this.attachEvent("onBeforeSort",dhtmlx.bind(function(){this._settings.sort=null},this))},_init_group_data_event:function(a,b){a.attachEvent("onClearAll",dhtmlx.bind(function(){this.ungroup(!1)},b))},sum:function(a,
b){var a=dhtmlx.Template.setter(a),b=b||this.data,c=0;b.each(function(b){c+=a(b)*1});return c},min:function(a,b){var a=dhtmlx.Template.setter(a),b=b||this.data,c=Infinity;b.each(function(b){a(b)*1<c&&(c=a(b)*1)});return c*1},max:function(a,b){var a=dhtmlx.Template.setter(a),b=b||this.data,c=-Infinity;b.each(function(b){a(b)*1>c&&(c=a(b)*1)});return c},_split_data_by:function(a){var b=function(a,b){a=dhtmlx.Template.setter(a);return a(b[0])},c=dhtmlx.Template.setter(a.by);a.map[c]||(a.map[c]=[c,b]);
var d={},e=[];this.data.each(function(a){var b=c(a);d[b]||(e.push({id:b}),d[b]=dhtmlx.toArray());d[b].push(a)});for(var f in a.map){var g=a.map[f][1]||b;typeof g!="function"&&(g=this[g]);for(var h=0;h<e.length;h++)e[h][f]=g.call(this,a.map[f][0],d[e[h].id])}this._not_grouped_data=this.data;this.data=new dhtmlx.DataStore;this.data.provideApi(this,!0);this._init_group_data_event(this.data,this);this.parse(e,"json")},group:function(a,b){this.ungroup(!1);this._split_data_by(a);b!==!1&&this.render()},
ungroup:function(a){if(this._not_grouped_data)this.data=this._not_grouped_data,this.data.provideApi(this,!0);a!==!1&&this.render()},group_setter:function(a){return a},sort_setter:function(a){typeof a!="object"&&(a={by:a});this._mergeSettings(a,{as:"string",dir:"asc"});return a}};
dhtmlx.KeyEvents={_init:function(){dhtmlx.event(this._obj,"keypress",this._onKeyPress,this)},_onKeyPress:function(a){var a=a||event,b=a.which||a.keyCode;this.callEvent(this._edit_id?"onEditKeyPress":"onKeyPress",[b,a.ctrlKey,a.shiftKey,a])}};
dhtmlx.MouseEvents={_init:function(){this.on_click&&(dhtmlx.event(this._obj,"click",this._onClick,this),dhtmlx.event(this._obj,"contextmenu",this._onContext,this));this.on_dblclick&&dhtmlx.event(this._obj,"dblclick",this._onDblClick,this);this.on_mouse_move&&(dhtmlx.event(this._obj,"mousemove",this._onMouse,this),dhtmlx.event(this._obj,dhtmlx._isIE?"mouseleave":"mouseout",this._onMouse,this))},_onClick:function(a){return this._mouseEvent(a,this.on_click,"ItemClick")},_onDblClick:function(a){return this._mouseEvent(a,
this.on_dblclick,"ItemDblClick")},_onContext:function(a){var b=dhtmlx.html.locate(a,this._id);if(b&&!this.callEvent("onBeforeContextMenu",[b,a]))return dhtmlx.html.preventEvent(a)},_onMouse:function(a){dhtmlx._isIE&&(a=document.createEventObject(event));this._mouse_move_timer&&window.clearTimeout(this._mouse_move_timer);this.callEvent("onMouseMoving",[a]);this._mouse_move_timer=window.setTimeout(dhtmlx.bind(function(){a.type=="mousemove"?this._onMouseMove(a):this._onMouseOut(a)},this),500)},_onMouseMove:function(a){this._mouseEvent(a,
this.on_mouse_move,"MouseMove")||this.callEvent("onMouseOut",[a||event])},_onMouseOut:function(a){this.callEvent("onMouseOut",[a||event])},_mouseEvent:function(a,b,c){for(var a=a||event,d=a.target||a.srcElement,e="",f=null,g=!1;d&&d.parentNode;){if(!g&&d.getAttribute&&(f=d.getAttribute(this._id))){d.getAttribute("userdata")&&this.callEvent("onLocateData",[f,d]);if(!this.callEvent("on"+c,[f,a,d]))return;g=!0}if(e=d.className)if(e=e.split(" "),e=e[0]||e[1],b[e])return b[e].call(this,a,f,d);d=d.parentNode}return g}};
dhtmlx.Settings={_init:function(){this._settings=this.config={}},define:function(a,b){return typeof a=="object"?this._parseSeetingColl(a):this._define(a,b)},_define:function(a,b){var c=this[a+"_setter"];return this._settings[a]=c?c.call(this,b):b},_parseSeetingColl:function(a){if(a)for(var b in a)this._define(b,a[b])},_parseSettings:function(a,b){var c=dhtmlx.extend({},b);typeof a=="object"&&!a.tagName&&dhtmlx.extend(c,a);this._parseSeetingColl(c)},_mergeSettings:function(a,b){for(var c in b)switch(typeof a[c]){case "object":a[c]=
this._mergeSettings(a[c]||{},b[c]);break;case "undefined":a[c]=b[c]}return a},_parseContainer:function(a,b,c){if(typeof a=="object"&&!a.tagName)a=a.container;this._obj=dhtmlx.toNode(a);if(!this._obj&&c)this._obj=c(a);this._obj.className+=" "+b;this._obj.onselectstart=function(){return!1};this._dataobj=this._obj},_set_type:function(a){if(typeof a=="object")return this.type_setter(a);this.type=dhtmlx.extend({},this.types[a]);this.customize()},customize:function(a){a&&dhtmlx.extend(this.type,a);this.type._item_start=
dhtmlx.Template.fromHTML(this.template_item_start(this.type));this.type._item_end=this.template_item_end(this.type);this.render()},type_setter:function(a){this._set_type(typeof a=="object"?dhtmlx.Type.add(this,a):a);return a},template_setter:function(a){return this.type_setter({template:a})},css_setter:function(a){this._obj.className+=" "+a;return a}};dhtmlx.compat=function(a,b){if(dhtmlx.compat[a])dhtmlx.compat[a](b)};
(function(){if(!window.dhtmlxError){var a=function(){};window.dhtmlxError={catchError:a,throwError:a};window.convertStringToBoolean=function(a){return!!a};window.dhtmlxEventable=function(a){dhtmlx.extend(a,dhtmlx.EventSystem)};var b={getXMLTopNode:function(){},doXPath:function(a){return dhtmlx.DataDriver.xml.xpath(this.xml,a)},xmlDoc:{responseXML:!0}};dhtmlx.compat.dataProcessor=function(a){var d="_sendData",e="_in_progress",f="_tMode",g="_waitMode";a[d]=function(a,c){if(a){c&&(this[e][c]=(new Date).valueOf());
if(!this.callEvent("onBeforeDataSending",c?[c,this.getState(c)]:[]))return!1;var d=this,i=this.serverProcessor;this[f]!="POST"?dhtmlx.ajax().get(i+(i.indexOf("?")!=-1?"&":"?")+this.serialize(a,c),"",function(a,c){b.xml=dhtmlx.DataDriver.xml.checkResponse(a,c);d.afterUpdate(d,null,null,null,b)}):dhtmlx.ajax().post(i,this.serialize(a,c),function(a,c){b.xml=dhtmlx.DataDriver.xml.checkResponse(a,c);d.afterUpdate(d,null,null,null,b)});this[g]++}}}}})();if(!dhtmlx.attaches)dhtmlx.attaches={};
dhtmlx.attaches.attachAbstract=function(a,b){var c=document.createElement("DIV");c.id="CustomObject_"+dhtmlx.uid();c.style.width="100%";c.style.height="100%";c.cmp="grid";document.body.appendChild(c);this.attachObject(c.id);b.container=c.id;var d=this.vs[this.av];d.grid=new window[a](b);d.gridId=c.id;d.gridObj=c;d.grid.setSizes=function(){this.resize?this.resize():this.render()};var e="_viewRestore";return this.vs[this[e]()].grid};
dhtmlx.attaches.attachDataView=function(a){return this.attachAbstract("dhtmlXDataView",a)};dhtmlx.attaches.attachChart=function(a){return this.attachAbstract("dhtmlXChart",a)};dhtmlx.compat.layout=function(){};
dhtmlx.DataDriver.dhtmlxgrid={_grid_getter:"_get_cell_value",toObject:function(a){return this._grid=a},getRecords:function(a){return a.rowsBuffer},getDetails:function(a){for(var b={},c=0;c<this._grid.getColumnsNum();c++)b["data"+c]=this._grid[this._grid_getter](a,c);return b},getInfo:function(){return{_size:0,_from:0}}};
dhtmlx.Canvas={_init:function(){this._canvas_labels=[]},_prepareCanvas:function(a){this._canvas=dhtmlx.html.create("canvas",{width:a.offsetWidth,height:a.offsetHeight});a.appendChild(this._canvas);!this._canvas.getContext&&dhtmlx._isIE&&(dhtmlx.require("thirdparty/excanvas/excanvas.js"),G_vmlCanvasManager.init_(document),G_vmlCanvasManager.initElement(this._canvas));return this._canvas},getCanvas:function(a){return(this._canvas||this._prepareCanvas(this._obj)).getContext(a||"2d")},_resizeCanvas:function(){this._canvas&&
(this._canvas.setAttribute("width",this._canvas.parentNode.offsetWidth),this._canvas.setAttribute("height",this._canvas.parentNode.offsetHeight))},renderText:function(a,b,c,d,e){if(c){var f=dhtmlx.html.create("DIV",{"class":"dhx_canvas_text"+(d?" "+d:""),style:"left:"+a+"px; top:"+b+"px;"},c);this._obj.appendChild(f);this._canvas_labels.push(f);if(e)f.style.width=e+"px";return f}},renderTextAt:function(a,b,c,d,e,f,g){var h=this.renderText.call(this,c,d,e,f,g);if(h){if(a)h.style.top=a=="middle"?parseInt(d-
h.offsetHeight/2,10)+"px":d-h.offsetHeight+"px";if(b)h.style.left=b=="left"?c-h.offsetWidth+"px":parseInt(c-h.offsetWidth/2,10)+"px"}return h},clearCanvas:function(){for(var a=0;a<this._canvas_labels.length;a++)this._obj.removeChild(this._canvas_labels[a]);this._canvas_labels=[];if(this._obj._htmlmap)this._obj._htmlmap.parentNode.removeChild(this._obj._htmlmap),this._obj._htmlmap=null;this.getCanvas().clearRect(0,0,this._canvas.offsetWidth,this._canvas.offsetHeight)}};
dhtmlXChart=function(a){this.name="Chart";this.version="3.0";dhtmlx.extend(this,dhtmlx.Settings);this._parseContainer(a,"dhx_chart");dhtmlx.extend(this,dhtmlx.AtomDataLoader);dhtmlx.extend(this,dhtmlx.DataLoader);this.data.provideApi(this,!0);dhtmlx.extend(this,dhtmlx.EventSystem);dhtmlx.extend(this,dhtmlx.MouseEvents);dhtmlx.extend(this,dhtmlx.Destruction);dhtmlx.extend(this,dhtmlx.Canvas);dhtmlx.extend(this,dhtmlx.Group);dhtmlx.extend(this,dhtmlx.AutoTooltip);for(var b in dhtmlx.chart)dhtmlx.extend(this,
dhtmlx.chart[b]);this._parseSettings(a,{color:"RAINBOW",alpha:"1",label:!1,value:"{obj.value}",padding:{},view:"pie",lineColor:"#ffffff",cant:0.5,width:15,labelWidth:100,line:{},item:{},shadow:!0,gradient:!1,border:!0,labelOffset:20,origin:"auto"});this._series=[this._settings];this.data.attachEvent("onStoreUpdated",dhtmlx.bind(function(){this.render()},this));this.attachEvent("onLocateData",this._switchSerie)};
dhtmlXChart.prototype={_id:"dhx_area_id",on_click:{},on_dblclick:{},on_mouse_move:{},bind:function(){dhx.BaseBind.legacyBind.apply(this,arguments)},sync:function(){dhx.BaseBind.legacySync.apply(this,arguments)},resize:function(){this._resizeCanvas();this.render()},view_setter:function(a){if(typeof this._settings.offset=="undefined")this._settings.offset=a=="area"||a=="stackedArea"?!1:!0;return a},render:function(){if(this.callEvent("onBeforeRender",[this.data])){this.clearCanvas();this._settings.legend&&
this._drawLegend(this.getCanvas(),this.data.getRange(),this._obj.offsetWidth,this._obj.offsetHeight);for(var a=this._getChartBounds(this._obj.offsetWidth,this._obj.offsetHeight),b=new dhtmlx.ui.Map(this._id),c=this._settings,d=0;d<this._series.length;d++)this._settings=this._series[d],this["pvt_render_"+this._settings.view](this.getCanvas(),this.data.getRange(),a.start,a.end,d,b);b.render(this._obj);this._settings=c}},value_setter:dhtmlx.Template.obj_setter,alpha_setter:dhtmlx.Template.obj_setter,
label_setter:dhtmlx.Template.obj_setter,lineColor_setter:dhtmlx.Template.obj_setter,pieInnerText_setter:dhtmlx.Template.obj_setter,gradient_setter:function(a){if(typeof a!="function"&&a&&(a===!0||a!="3d"))a="light";return a},colormap:{RAINBOW:function(a){var b=Math.floor(this.indexById(a.id)/this.dataCount()*1536);b==1536&&(b-=1);return this._rainbow[Math.floor(b/256)](b%256)}},color_setter:function(a){return this.colormap[a]||dhtmlx.Template.obj_setter(a)},legend_setter:function(a){if(!a){if(this.legendObj)this.legendObj.innerHTML=
"",this.legendObj=null;return!1}typeof a!="object"&&(a={template:a});this._mergeSettings(a,{width:150,height:18,layout:"y",align:"left",valign:"bottom",template:"",marker:{type:"square",width:25,height:15}});a.template=dhtmlx.Template.setter(a.template);return a},item_setter:function(a){typeof a!="object"&&(a={color:a,borderColor:a});this._mergeSettings(a,{radius:4,color:"#000000",borderColor:"#000000",borderWidth:2});a.color=dhtmlx.Template.setter(a.color);a.borderColor=dhtmlx.Template.setter(a.borderColor);
return a},line_setter:function(a){typeof a!="object"&&(a={color:a});this._mergeSettings(a,{width:3,color:"#d4d4d4"});a.color=dhtmlx.Template.setter(a.color);return a},padding_setter:function(a){typeof a!="object"&&(a={left:a,right:a,top:a,bottom:a});this._mergeSettings(a,{left:50,right:20,top:35,bottom:40});return a},xAxis_setter:function(a){if(!a)return!1;typeof a!="object"&&(a={template:a});this._mergeSettings(a,{title:"",color:"#000000",template:"{obj}",lines:!1});if(a.template)a.template=dhtmlx.Template.setter(a.template);
return a},yAxis_setter:function(a){this._mergeSettings(a,{title:"",color:"#000000",template:"{obj}",lines:!0});if(a.template)a.template=dhtmlx.Template.setter(a.template);return a},_drawScales:function(a,b,c,d,e,f,g){var h=this._drawYAxis(a,b,c,d,e,f);this._drawXAxis(a,b,c,d,g,h);return h},_drawXAxis:function(a,b,c,d,e,f){if(this._settings.xAxis){var g=c.x-0.5,h=parseInt(f?f:d.y,10)+0.5,k=d.x,j,i=!0;this._drawLine(a,g,h,k,h,this._settings.xAxis.color,1);for(var m=0;m<b.length;m++){this._settings.offset===
!0?j=g+e/2+m*e:(j=g+m*e,i=!!m);var l=this._settings.origin!="auto"&&this._settings.view=="bar"&&parseFloat(this._settings.value(b[m]))<this._settings.origin;this._drawXAxisLabel(j,h,b[m],i,l);this._settings.view_setter!="bar"&&this._drawXAxisLine(a,j,d.y,c.y)}this.renderTextAt(!0,!1,g,d.y+this._settings.padding.bottom-3,this._settings.xAxis.title,"dhx_axis_title_x",d.x-c.x);this._settings.xAxis.lines&&this._settings.offset&&this._drawLine(a,k+0.5,d.y,k+0.5,c.y+0.5,this._settings.xAxis.color,0.2)}},
_drawYAxis:function(a,b,c,d,e,f){var g,h={};if(this._settings.yAxis){var k=c.x-0.5,j=d.y,i=c.y,m=d.y;this._drawLine(a,k,j,k,i,this._settings.yAxis.color,1);this._settings.yAxis.step&&(g=parseFloat(this._settings.yAxis.step));if(typeof this._settings.yAxis.step=="undefined"||typeof this._settings.yAxis.start=="undefined"||typeof this._settings.yAxis.end=="undefined")h=this._calculateScale(e,f),e=h.start,f=h.end,g=h.step,this._settings.yAxis.end=f,this._settings.yAxis.start=e;this._setYAxisTitle(c,
d);if(g!==0){if(f==e)return j;for(var l=(j-i)*g/(f-e),n=0,o=e;o<=f;o+=g){h.fixNum&&(o=parseFloat((new Number(o)).toFixed(h.fixNum)));var p=Math.floor(j-n*l)+0.5;!(o==e&&this._settings.origin=="auto")&&this._settings.yAxis.lines&&this._drawLine(a,k,p,d.x,p,this._settings.yAxis.color,0.2);o==this._settings.origin&&(m=p);var q=o;if(g<1)var t=Math.min(this._log10(g),e===0?0:this._log10(e)),s=Math.pow(10,-t),q=Math.round(o*s)/s;this.renderText(0,p-5,this._settings.yAxis.template(q.toString()),"dhx_axis_item_y",
c.x-5);n++}return m}}},_setYAxisTitle:function(a,b){var c=this.renderTextAt("middle",!1,0,parseInt((b.y-a.y)/2+a.y,10),this._settings.yAxis.title,"dhx_axis_title_y");if(c)c.style.left=(dhtmlx.env.transform?(c.offsetHeight-c.offsetWidth)/2:0)+"px"},_calculateScale:function(a,b){if(this._settings.origin!="auto"&&this._settings.origin<a)a=this._settings.origin;var c,d,e;c=(b-a)/8||1;var f=Math.floor(this._log10(c)),g=Math.pow(10,f),h=c/g,h=h>5?10:5;c=parseInt(h,10)*g;if(c>Math.abs(a))d=a<0?-c:0;else{var k=
Math.abs(a),j=Math.floor(this._log10(k)),i=k/Math.pow(10,j);d=Math.ceil(i*10)/10*Math.pow(10,j)-c;a<0&&(d=-d-2*c)}for(e=d;e<b;)e+=c,e=parseFloat((new Number(e)).toFixed(Math.abs(f)));return{start:d,end:e,step:c,fixNum:Math.abs(f)}},_getLimits:function(a){var b,c,d=arguments.length&&a=="h"?this._settings.xAxis:this._settings.yAxis;if(d&&typeof d.end!="undefined"&&typeof d.start!="undefined"&&d.step)b=parseFloat(d.end),c=parseFloat(d.start);else if(b=this.max(this._series[0].value),c=this.min(this._series[0].value),
this._series.length>1)for(var e=1;e<this._series.length;e++){var f=this.max(this._series[e].value),g=this.min(this._series[e].value);f>b&&(b=f);g<c&&(c=g)}return{max:b,min:c}},_log10:function(a){var b="log";return Math.floor(Math[b](a)/Math.LN10)},_drawXAxisLabel:function(a,b,c,d,e){if(this._settings.xAxis){var f=this.renderTextAt(e,d,a,b,this._settings.xAxis.template(c));f&&(f.className+=" dhx_axis_item_x")}},_drawXAxisLine:function(a,b,c,d){this._settings.xAxis&&this._settings.xAxis.lines&&this._drawLine(a,
b,c,b,d,this._settings.xAxis.color,0.2)},_drawLine:function(a,b,c,d,e,f,g){a.strokeStyle=f;a.lineWidth=g;a.beginPath();a.moveTo(b,c);a.lineTo(d,e);a.stroke()},_getRelativeValue:function(a,b){var c,d=1;if(b!=a){if(c=b-a,Math.abs(c)<1)for(;Math.abs(c)<1;)d*=10,c*=d}else c=a;return[c,d]},_rainbow:[function(a){return"#FF"+dhtmlx.math.toHex(a/2,2)+"00"},function(a){return"#FF"+dhtmlx.math.toHex(a/2+128,2)+"00"},function(a){return"#"+dhtmlx.math.toHex(255-a,2)+"FF00"},function(a){return"#00FF"+dhtmlx.math.toHex(a,
2)},function(a){return"#00"+dhtmlx.math.toHex(255-a,2)+"FF"},function(a){return"#"+dhtmlx.math.toHex(a,2)+"00FF"}],addSeries:function(a){var b=this._settings;this._settings=dhtmlx.extend({},b);this._parseSettings(a,{});this._series.push(this._settings);this._settings=b},_switchSerie:function(a,b){this._active_serie=b.getAttribute("userdata");if(this._series[this._active_serie]){for(var c=0;c<this._series.length;c++){var d=this._series[c].tooltip;d&&d.disable()}(d=this._series[this._active_serie].tooltip)&&
d.enable()}},_drawLegend:function(a,b){var c=0,d=0,e=this._settings.legend,f,g,h=this._settings.legend.layout!="x"?"width:"+e.width+"px":"";if(this.legendObj)this.legendObj.innerHTML="";var k=dhtmlx.html.create("DIV",{"class":"dhx_chart_legend",style:"left:"+c+"px; top:"+d+"px;"+h},"");this.legendObj=k;this._obj.appendChild(k);var j=[];if(e.values)for(i=0;i<e.values.length;i++)j.push(this._drawLegendText(k,e.values[i].text));else for(var i=0;i<b.length;i++)j.push(this._drawLegendText(k,e.template(b[i])));
g=k.offsetWidth;f=k.offsetHeight;this._settings.legend.width=g;this._settings.legend.height=f;g<this._obj.offsetWidth&&(e.layout=="x"&&e.align=="center"&&(c=(this._obj.offsetWidth-g)/2),e.align=="right"&&(c=this._obj.offsetWidth-g));f<this._obj.offsetHeight&&(e.valign=="middle"&&e.align!="center"&&e.layout!="x"?d=(this._obj.offsetHeight-f)/2:e.valign=="bottom"&&(d=this._obj.offsetHeight-f));k.style.left=c+"px";k.style.top=d+"px";for(i=0;i<j.length;i++){var m=j[i],l=e.values?e.values[i].color:this._settings.color.call(this,
b[i]);this._drawLegendMarker(a,m.offsetLeft+c,m.offsetTop+d,l)}j=null},_drawLegendText:function(a,b){var c="";this._settings.legend.layout=="x"&&(c="float:left;");var d=dhtmlx.html.create("DIV",{style:c+"padding-left:"+(10+this._settings.legend.marker.width)+"px","class":"dhx_chart_legend_item"},b);a.appendChild(d);return d},_drawLegendMarker:function(a,b,c,d){var e=this._settings.legend;a.strokeStyle=a.fillStyle=d;a.lineWidth=e.marker.height;a.lineCap=e.marker.type;a.beginPath();b+=a.lineWidth/2+
5;c+=a.lineWidth/2+3;a.moveTo(b,c);var f=b+e.marker.width-e.marker.height+1;a.lineTo(f,c);a.stroke()},_getChartBounds:function(a,b){var c,d,e,f;c=this._settings.padding.left;d=this._settings.padding.top;e=a-this._settings.padding.right;f=b-this._settings.padding.bottom;if(this._settings.legend){var g=this._settings.legend,h=this._settings.legend.width,k=this._settings.legend.height;g.layout=="x"?g.valign=="center"?g.align=="right"?e-=h:g.align=="left"&&(c+=h):g.valign=="bottom"?f-=k:d+=k:g.align==
"right"?e-=h:g.align=="left"&&(c+=h)}return{start:{x:c,y:d},end:{x:e,y:f}}},_getStackedLimits:function(a){var b,c;if(this._settings.yAxis&&typeof this._settings.yAxis.end!="undefied"&&typeof this._settings.yAxis.start!="undefied"&&this._settings.yAxis.step)b=parseFloat(this._settings.yAxis.end),c=parseFloat(this._settings.yAxis.start);else{for(var d=0;d<a.length;d++){a[d].$sum=0;a[d].$min=Infinity;for(var e=0;e<this._series.length;e++){var f=parseFloat(this._series[e].value(a[d]));if(!isNaN(f)&&(a[d].$sum+=
f,f<a[d].$min))a[d].$min=f}}b=-Infinity;c=Infinity;for(d=0;d<a.length;d++){if(a[d].$sum>b)b=a[d].$sum;if(a[d].$min<c)c=a[d].$min}c>0&&(c=0)}return{max:b,min:c}},_setBarGradient:function(a,b,c,d,e,f,g,h){var k,j;f=="light"?(k=h=="x"?a.createLinearGradient(b,c,d,c):a.createLinearGradient(b,c,b,e),k.addColorStop(0,"#FFFFFF"),k.addColorStop(0.9,g),k.addColorStop(1,g),j=2):(a.globalAlpha=0.37,j=0,k=h=="x"?a.createLinearGradient(b,e,b,c):a.createLinearGradient(b,c,d,c),k.addColorStop(0,"#000000"),k.addColorStop(0.5,
"#FFFFFF"),k.addColorStop(0.6,"#FFFFFF"),k.addColorStop(1,"#000000"));return{gradient:k,offset:j}}};dhtmlx.compat("layout");
